BEGIN;

CREATE TABLE IF NOT EXISTS USER_INFO
(
    ID                 BIGSERIAL
        PRIMARY KEY,
    USERNAME           VARCHAR(255) NOT NULL,
    EMAIL              VARCHAR(255) NOT NULL,
    PASSWORD           TEXT         NOT NULL,
    CREATED_BY         VARCHAR(255),
    CREATED_DATE       TIMESTAMP(6),
    LAST_MODIFIED_BY   VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS USER_INFO_USERNAME_UINDEX ON USER_INFO (USERNAME);
CREATE UNIQUE INDEX IF NOT EXISTS USER_INFO_EMAIL_UINDEX ON USER_INFO (EMAIL);

COMMIT;
