BEGIN;

CREATE TABLE IF NOT EXISTS APP_USER
(
    ID                 BIGSERIAL
        PRIMARY KEY,
    USERNAME           VARCHAR(255) UNIQUE NOT NULL,
    EMAIL              VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD           TEXT         NOT NULL,
    CREATED_BY         VARCHAR(255),
    CREATED_DATE       TIMESTAMP(6),
    LAST_MODIFIED_BY   VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP(6)
);

CREATE UNIQUE INDEX IF NOT EXISTS APP_USER_USERNAME_UINDEX ON APP_USER (USERNAME);
CREATE UNIQUE INDEX IF NOT EXISTS APP_USER_EMAIL_UINDEX ON APP_USER (EMAIL);

COMMIT;
